/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleAction: typeof import('./src/components/ArticleAction.vue')['default']
    ArticleForm: typeof import('./src/components/ArticleForm.vue')['default']
    CommentSection: typeof import('./src/components/CommentSection.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MdPreview: typeof import('./src/components/MdPreview.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavSearch: typeof import('./src/components/NavSearch.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFelx: typeof import('naive-ui')['NFelx']
    NFlex: typeof import('naive-ui')['NFlex']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH3: typeof import('naive-ui')['NH3']
    NHr: typeof import('naive-ui')['NHr']
    NIcon: typeof import('naive-ui')['NIcon']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NP: typeof import('naive-ui')['NP']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Sider: typeof import('./src/components/Sider.vue')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
  }
}
