/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleAction: typeof import('./src/components/ArticleAction.vue')['default']
    ArticleForm: typeof import('./src/components/ArticleForm.vue')['default']
    CommentSection: typeof import('./src/components/CommentSection.vue')['default']
    EditUserDialog: typeof import('./src/components/EditUserDialog.vue')['default']
    EntryCommentBar: typeof import('./src/components/EntryCommentBar.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MdPreview: typeof import('./src/components/MdPreview.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavSearch: typeof import('./src/components/NavSearch.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NewUserDialog: typeof import('./src/components/NewUserDialog.vue')['default']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Sider.vue')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
